-- MySQL Script generated by MySQL Workbench
-- 04/27/17 22:50:34
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Eventos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Eventos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Eventos` DEFAULT CHARACTER SET utf8 ;
USE `Eventos` ;

-- -----------------------------------------------------
-- Table `Eventos`.`Pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Eventos`.`Pessoa` (
  `idPessoa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  PRIMARY KEY (`idPessoa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Eventos`.`ResponsavelEvento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Eventos`.`ResponsavelEvento` (
  `idResponsavelEvento` INT NOT NULL,
  `rg` INT NOT NULL,
  `Pessoa_idPessoa` INT NOT NULL,
  PRIMARY KEY (`idResponsavelEvento`),
  INDEX `fk_ResponsavelEvento_Pessoa_idx` (`Pessoa_idPessoa` ASC),
  CONSTRAINT `fk_ResponsavelEvento_Pessoa`
    FOREIGN KEY (`Pessoa_idPessoa`)
    REFERENCES `Eventos`.`Pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Eventos`.`PrestadoraServico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Eventos`.`PrestadoraServico` (
  `idPrestadoraServico` INT NOT NULL,
  `CNPJ` INT NOT NULL,
  `Pessoa_idPessoa` INT NOT NULL,
  PRIMARY KEY (`idPrestadoraServico`),
  INDEX `fk_PrestadoraServico_Pessoa1_idx` (`Pessoa_idPessoa` ASC),
  CONSTRAINT `fk_PrestadoraServico_Pessoa1`
    FOREIGN KEY (`Pessoa_idPessoa`)
    REFERENCES `Eventos`.`Pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Eventos`.`ClienteEvento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Eventos`.`ClienteEvento` (
  `idClienteEvento` INT NOT NULL AUTO_INCREMENT,
  `statusPagamento` TINYINT(1) NULL,
  `Pessoa_idPessoa` INT NOT NULL,
  PRIMARY KEY (`idClienteEvento`),
  INDEX `fk_ClienteEvento_Pessoa1_idx` (`Pessoa_idPessoa` ASC),
  CONSTRAINT `fk_ClienteEvento_Pessoa1`
    FOREIGN KEY (`Pessoa_idPessoa`)
    REFERENCES `Eventos`.`Pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Eventos`.`Evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Eventos`.`Evento` (
  `idEvento` INT NOT NULL AUTO_INCREMENT,
  `tipoEvento` VARCHAR(500) NULL,
  `data` DATE NULL,
  `descrição` VARCHAR(500) NULL,
  PRIMARY KEY (`idEvento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Eventos`.`Ingresso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Eventos`.`Ingresso` (
  `idIngresso` INT NOT NULL AUTO_INCREMENT,
  `numero` INT NULL,
  `valor` DOUBLE NULL,
  `ClienteEvento_idClienteEvento` INT NOT NULL,
  `Evento_idEvento` INT NOT NULL,
  PRIMARY KEY (`idIngresso`),
  INDEX `fk_Ingresso_ClienteEvento1_idx` (`ClienteEvento_idClienteEvento` ASC),
  INDEX `fk_Ingresso_Evento1_idx` (`Evento_idEvento` ASC),
  CONSTRAINT `fk_Ingresso_ClienteEvento1`
    FOREIGN KEY (`ClienteEvento_idClienteEvento`)
    REFERENCES `Eventos`.`ClienteEvento` (`idClienteEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ingresso_Evento1`
    FOREIGN KEY (`Evento_idEvento`)
    REFERENCES `Eventos`.`Evento` (`idEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Eventos`.`Servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Eventos`.`Servico` (
  `idServico` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NULL,
  `valor` DOUBLE NULL,
  `descricao` VARCHAR(400) NULL,
  `PrestadoraServico_idPrestadoraServico` INT NOT NULL,
  `Evento_idEvento` INT NOT NULL,
  PRIMARY KEY (`idServico`),
  INDEX `fk_Servico_PrestadoraServico1_idx` (`PrestadoraServico_idPrestadoraServico` ASC),
  INDEX `fk_Servico_Evento1_idx` (`Evento_idEvento` ASC),
  CONSTRAINT `fk_Servico_PrestadoraServico1`
    FOREIGN KEY (`PrestadoraServico_idPrestadoraServico`)
    REFERENCES `Eventos`.`PrestadoraServico` (`idPrestadoraServico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Servico_Evento1`
    FOREIGN KEY (`Evento_idEvento`)
    REFERENCES `Eventos`.`Evento` (`idEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Eventos`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Eventos`.`Endereco` (
  `cep` VARCHAR(500) NULL,
  `cidade` VARCHAR(45) NULL,
  `idEnd` INT NOT NULL AUTO_INCREMENT,
  `complemento` VARCHAR(45) NULL,
  `Pessoa_idPessoa` INT NOT NULL,
  PRIMARY KEY (`idEnd`),
  INDEX `fk_Endereco_Pessoa1_idx` (`Pessoa_idPessoa` ASC),
  CONSTRAINT `fk_Endereco_Pessoa1`
    FOREIGN KEY (`Pessoa_idPessoa`)
    REFERENCES `Eventos`.`Pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
